/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package partymanager;

import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Andredur
 */
public class chooseParty extends javax.swing.JFrame {
    private Action action = new Action();
    /**
     * Creates new form chooseParty
     */
    public chooseParty() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        File_Chooser = new javax.swing.JFileChooser();
        New_Party = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        AdminName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        AdminPassword = new javax.swing.JPasswordField();
        Create = new javax.swing.JButton();
        ExistingButton = new javax.swing.JButton();
        NewButton = new javax.swing.JButton();

        FileNameExtensionFilter filter = new FileNameExtensionFilter("Serializable","ser");
        File_Chooser.setFileFilter(filter);
        File_Chooser.setAcceptAllFileFilterUsed(false);

        New_Party.setTitle("Create new party");

        jLabel1.setText("Admin:");

        jLabel2.setText("Password:");

        Create.setText("Create");
        Create.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout New_PartyLayout = new javax.swing.GroupLayout(New_Party.getContentPane());
        New_Party.getContentPane().setLayout(New_PartyLayout);
        New_PartyLayout.setHorizontalGroup(
            New_PartyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(New_PartyLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(New_PartyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(New_PartyLayout.createSequentialGroup()
                        .addGroup(New_PartyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(New_PartyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AdminName, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
                            .addComponent(AdminPassword)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, New_PartyLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Create)))
                .addContainerGap())
        );
        New_PartyLayout.setVerticalGroup(
            New_PartyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(New_PartyLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(New_PartyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(AdminName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(New_PartyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(AdminPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Create)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ExistingButton.setText("Use existing party");
        ExistingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExistingButtonActionPerformed(evt);
            }
        });

        NewButton.setText("Create new party");
        NewButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NewButton)
                    .addComponent(ExistingButton))
                .addContainerGap(102, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {ExistingButton, NewButton});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(ExistingButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                .addComponent(NewButton)
                .addGap(38, 38, 38))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {ExistingButton, NewButton});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NewButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewButtonActionPerformed
        New_Party.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_NewButtonActionPerformed

    private void ExistingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExistingButtonActionPerformed
        int result = File_Chooser.showOpenDialog(this);
        if(result == JFileChooser.APPROVE_OPTION)
        {
            File file = File_Chooser.getSelectedFile();
            action.ImportFile(file);
            
        }
        
        File_Chooser.setSelectedFile(new File(""));
        this.setVisible(false);
        System.out.println("Filechooser openened");
        login log = new login();
        log.setVisible(true);
    }//GEN-LAST:event_ExistingButtonActionPerformed

    private void CreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateActionPerformed
        this.setVisible(false);
        String name = AdminName.getText();
        String password = AdminPassword.getText();
        System.out.println("Naam: "+name+"\nPassword: "+password);
        Person admin = new Person(name,true);
        PartyManager.party.addPartyMember(admin);
        admin ad = new admin();
        ad.updateAllpersons();
        New_Party.setVisible(false);
        ad.setVisible(true);
    }//GEN-LAST:event_CreateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(chooseParty.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(chooseParty.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(chooseParty.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(chooseParty.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new chooseParty().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AdminName;
    private javax.swing.JPasswordField AdminPassword;
    private javax.swing.JButton Create;
    private javax.swing.JButton ExistingButton;
    private javax.swing.JFileChooser File_Chooser;
    private javax.swing.JButton NewButton;
    private javax.swing.JDialog New_Party;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
